"""Initial

Revision ID: 10f50c15aeee
Revises: 
Create Date: 2022-06-13 15:28:21.511630

"""
from alembic import op
import sqlalchemy as sa
import core

# revision identifiers, used by Alembic.
revision = "10f50c15aeee"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", core.db.types.UUID(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categories",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", core.db.types.UUID(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "areas_translation",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", core.db.types.UUID(length=36), nullable=False),
        sa.Column("area_id", core.db.types.UUID(length=36), nullable=False),
        sa.Column("language_code", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("area_id", "language_code", name="uq_area_id_language_code"),
    )
    op.create_index(op.f("ix_areas_translation_language_code"), "areas_translation", ["language_code"], unique=False)
    op.create_table(
        "categories_translation",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", core.db.types.UUID(length=36), nullable=False),
        sa.Column("category_id", core.db.types.UUID(length=36), nullable=False),
        sa.Column("language_code", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "language_code", name="uq_category_id_language_code"),
    )
    op.create_index(
        op.f("ix_categories_translation_language_code"), "categories_translation", ["language_code"], unique=False
    )
    op.create_table(
        "doctors",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", core.db.types.UUID(length=36), nullable=False),
        sa.Column("area_id", core.db.types.UUID(length=36), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=13, scale=2), nullable=True),
        sa.Column("phone_number", sa.String(length=13), nullable=True),
        sa.Column("working_hours", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "doctors_categories",
        sa.Column("id", core.db.types.UUID(length=36), nullable=False),
        sa.Column("doctor_id", core.db.types.UUID(length=36), nullable=False),
        sa.Column("category_id", core.db.types.UUID(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doctor_id", "category_id", name="uq_doctor_id_category_id"),
    )
    op.create_table(
        "doctors_translation",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", core.db.types.UUID(length=36), nullable=False),
        sa.Column("doctor_id", core.db.types.UUID(length=36), nullable=False),
        sa.Column("language_code", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doctor_id", "language_code", name="uq_doctor_id_language_code"),
    )
    op.create_index(
        op.f("ix_doctors_translation_language_code"), "doctors_translation", ["language_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_doctors_translation_language_code"), table_name="doctors_translation")
    op.drop_table("doctors_translation")
    op.drop_table("doctors_categories")
    op.drop_table("doctors")
    op.drop_index(op.f("ix_categories_translation_language_code"), table_name="categories_translation")
    op.drop_table("categories_translation")
    op.drop_index(op.f("ix_areas_translation_language_code"), table_name="areas_translation")
    op.drop_table("areas_translation")
    op.drop_table("categories")
    op.drop_table("areas")
    # ### end Alembic commands ###
